<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?=$pageTitle?></title>

        <!-- Bootstrap core CSS -->
        <link href="<?=WEB_ROOT?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?=WEB_ROOT?>/css/layouts/blog.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="blog-masthead">
            <div class="container">
                <nav class="blog-nav">
                    <a class="blog-nav-item active" href="<?=LINK_ROOT?>">Accueil</a>
                    <a class="blog-nav-item" href="<?=LINK_ROOT.'recette/categorie'?>">Categories</a>
                    <a class="blog-nav-item" href="<?=LINK_ROOT.'recette/chef'?>">Recettes de chef</a>
                    <a class="blog-nav-item" href="<?=LINK_ROOT.'recette/sante'?>">forme et santé</a>
                    <a class="blog-nav-item" href="<?=LINK_ROOT.'vente/livre'?>">livres</a>
                    <a class="blog-nav-item" href="<?=LINK_ROOT.'vente/restaurant'?>">Restaurants</a>
                    <a class="blog-nav-item" href="<?=LINK_ROOT.'video/index'?>">Video tuto</a>
                    <?php if((!empty($_SESSION['user'])) && $_SESSION['user']['role'] == "admin"): ?>
                        <a class="blog-nav-item" href="<?=LINK_ROOT.'admin/index'?>">Administration du site</a>
                    <?php endif; ?>
                </nav>
                <nav  class="blog-nav blog-nav-right">
                    <?php if(empty($_SESSION['user'])): ?>
                        <a class="blog-nav-item" href="<?=LINK_ROOT.'user/login'?>">Connexion</a>
                    <?php else :?>
                        <a class="blog-nav-item" href="<?=LINK_ROOT.'user/profil'?>">
                            <span class="glyphicon glyphicon-user"></span>
                        </a>
                        <a class="blog-nav-item" href="<?=LINK_ROOT.'user/logout'?>">Deconnexion</a>
                    <?php endif; ?>
                </nav>
            </div>
        </div>
        <div class="container">
            <div class="blog-header">
                <h1 class="blog-title">The Bootstrap Blog</h1>
                <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
            </div>
            <div class="row">
                <div class="col-sm-8 blog-main">
                    <?=$content_view?>
                      

                </div><!-- /.blog-main -->
                <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
                    <?php
                        $router->dispatchModule("Test", "liste", array("param1"=>"titi",
                                                                       "param2"=>10));
                    ?>
                   
                </div><!-- /.blog-sidebar -->
            </div><!-- /.row -->
        </div><!-- /.container -->
        <div class="blog-footer">
            <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
            <p>
                <a href="#">Back to top</a>
            </p>
        </div>


        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="<?=WEB_ROOT?>/js/bootstrap.min.js"></script>
    </body>
</html>
