<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?=$pageTitle?></title>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Styles -->
        <link href="<?=WEB_ROOT?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?=WEB_ROOT?>/css/layouts/carousel.css" rel="stylesheet">
        <link href="<?=WEB_ROOT?>/css/chefdesfourneaux.css" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    </head>
    
        <!-- NAVBAR
    ================================================== -->
    <body>
        <div class="navbar-wrapper">
            <div class="container">
                
                <nav class="navbar navbar-inverse navbar-static-top">
                    <div class="container">

                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand lienChefDesFourneaux activeLink" href="<?=LINK_ROOT?>">Chef des fourneaux...</a>
                            <div class="navbar panier col-xs-6 col-md-4" id="panier">                                
                                <?php if(!empty($_SESSION['user'])): ?>
                                <a class="btn btn-default lienPanier" href="<?=LINK_ROOT.'panier/indexpanier/'.$_SESSION['user']['id_user']?>">
                                    <span class="glyphicon glyphicon-shopping-cart"></span> 
                                    Votre Panier : 
                                    <div class="panierContent" id="panierContent">0 </div>
                                    articles
                                </a>
                                <?php else: ?>
                                    <a class="btn btn-default lienPanier" href="<?=LINK_ROOT.'vente/indexproduit/'?>"> Acheter des produits</a>
                                <?php endif; ?>
                            </div>
                            
                        </div>
                        

                        <div id="navbar" class="navbar-collapse collapse">

                            <ul class="nav navbar-nav">
                            
                                <li class="lienChefDesFourneaux"><a  href="<?=LINK_ROOT.'recette/index'?>">Categories</a></li>
                                <li class="lienChefDesFourneaux"><a  href="<?=LINK_ROOT.'recette/indexchef'?>">Recettes de chef</a></li>
                                <li class="lienChefDesFourneaux"><a href="<?=LINK_ROOT.'recette/indexcategorie/3'?>">Forme et santé</a></li>
                                <li class="lienChefDesFourneaux"><a href="<?=LINK_ROOT.'vente/indexlivre'?>">Livres de cuisine</a></li>
                                <li class="lienChefDesFourneaux"><a href="<?=LINK_ROOT.'vente/indexrestaurant'?>">Restaurants de nos chefs</a></li>
                                <li class="lienChefDesFourneaux"><a href="<?=LINK_ROOT.'vente/indexproduit'?>">Produits en ventes</a></li>
                                <li class="dropdown lienChefDesFourneaux">
                                    <?php if(empty($_SESSION['user'])):?>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">S'inscrire / Se connecter <span class="caret"></span></a>
                                    <?php else :?>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Bienvenue <?=$_SESSION['user']['pseudo']?> <span class="caret"></span></a>
                                    <?php endif ;?>



                                    <ul class="dropdown-menu" role="menu">
                                        <?php if(empty($_SESSION['user'])): ?>
                                        <li><a href="<?=LINK_ROOT.'user/inscription'?>">Inscription</a></li>
                                        <li><a href="<?=LINK_ROOT.'user/login'?>">Connexion</a></li>
                                        <?php else :?>
                                        <li><a href="<?=LINK_ROOT.'user/profil'?>">
                                                <span class="glyphicon glyphicon-user"></span>
                                                Profil
                                            </a>
                                        </li>
                                        <li><a class="blog-nav-item" href="<?=LINK_ROOT.'user/logout'?>">Deconnexion</a></li>
                                        <?php endif; 
                                        if((!empty($_SESSION['user'])) && $_SESSION['user']['role'] == "admin"): ?>
                                        <li class="divider"></li>
                                        <li class="dropdown-header">Administration du site</li>
                                        
                                        <li><a href="<?=LINK_ROOT.'admin/index'?>">Recettes</a></li>
                                        <li><a href="<?=LINK_ROOT.'adminproduit/index'?>">Produits</a></li>
                                        <li><a href="<?=LINK_ROOT.'admin/restaurant'?>">Restaurant</a></li>
                                        <li><a href="<?=LINK_ROOT.'admin/livre'?>">Livres de cuisine</a></li>
                                        <?php endif; ?>
                                        
                                    </ul> 
                                </li>
                            </ul>
                        </div> <!-- Fin navbar-header -->
                    </div> <!-- Fin container -->
                </nav>
            </div> <!-- Fin container -->
        </div> <!-- Fin navbar-wrapper --> 

        <div id="separator" class="separator"></div>
        

        <!-- Marketing messaging and featurettes
        ================================================== -->
        <div class="container marketing">
        
            <div class="content_view" id="content_view">
                <?=$content_view?>
            </div>
            <p><a href="<?=LINK_ROOT?>">Retour à l'accueil</a></p> 
  
            <!-- FOOTER -->
            <footer>
            <p class="pull-right"><a href="#">Back to top</a></p>
            <p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
            </footer>

        </div><!-- /.container -->


        
        <canvas id="easteregg"></canvas>



        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script-->
        <script src="<?=WEB_ROOT?>js/bootstrap/bootstrap.min.js"></script>
        <script src="<?=WEB_ROOT?>js/bootstrap/docs.min.js"></script>
        <script src="<?=WEB_ROOT?>js/chefdesfourneaux.js"></script>


        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="<?=WEB_ROOT?>/js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>