<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Site de recettes de cuisine et de vente d'électroménager">
        <link rel="shortcut icon" type="image/x-icon" href="<?=IMG_LINK_ROOT?>icons/iconSite.png" />
        <title><?=$pageTitle?></title>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Styles -->
        <link href="<?=WEB_ROOT?>/css/reset.css" rel="stylesheet">
        <link href="<?=WEB_ROOT?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?=WEB_ROOT?>/css/layouts/carousel.css" rel="stylesheet">
        <link href="<?=WEB_ROOT?>/css/chefdesfourneaux.css" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    </head>
    
        <!-- NAVBAR
    ================================================== -->
    <body>
    <div class="menu">
        <div class="navbar-wrapper">     
            <nav class="navbar navbar-static-top">
                <div class="containerNav">
                    <div class="container">
                        <div class="row">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <div class="col-md-6 logo">
                                <a class="navbar-brand lienChefDesFourneaux " href="<?=LINK_ROOT?>"><img src="<?=IMG_LINK_ROOT?>chefdesfourneauxlogo.png"></a>
                                Les meilleures recettes pour tous les goûts !
                            </div>
                            
                            <div class="animSiteFadeInNormal buttonNav col-md-6" >
                                <div class="col-md-6" id="connection">                               
                                    <button class="btn btn-default dropdown">
                                        <?php if(empty($_SESSION['user'])):?>
                                        <div class="dropdown-toggle animSiteFadeInNormal" data-toggle="dropdown" role="button" aria-expanded="false">S'inscrire / Se connecter <span class="caret"></span></div>
                                        <?php else :?>
                                        <div class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Bienvenue <?=$_SESSION['user']['pseudo']?> <span class="caret"></span></div>
                                        <?php endif ;?>

                                        <ul class="dropdown-menu" role="menu">
                                            <?php if(empty($_SESSION['user'])): ?>
                                            <li><a href="<?=LINK_ROOT.'user/inscription'?>">Inscription</a></li>
                                            <li><a href="<?=LINK_ROOT.'user/login'?>">Connexion</a></li>
                                            <li><a href="<?=LINK_ROOT.'user/motdepasseoublie'?>">Mot de passe oublié</a></li>
                                            <?php else :?>
                                            <li><a href="<?=LINK_ROOT.'user/profil'?>">
                                                    <span class="glyphicon glyphicon-user"></span>
                                                    Profil
                                                </a>
                                            </li>
                                            <li><a class="blog-nav-item" href="<?=LINK_ROOT.'user/logout'?>">Deconnexion</a></li>
                                            <?php endif; 
                                            if((!empty($_SESSION['user'])) && $_SESSION['user']['role'] == "admin"): ?>
                                            <li class="divider"></li>
                                            <li class="dropdown-header">Administration du site</li>
                                            
                                            <li><a href="<?=LINK_ROOT.'admin/index'?>">Recettes</a></li>
                                            <li><a href="<?=LINK_ROOT.'vente/indexproduit'?>">Produits</a></li>
                                            <li><a href="<?=LINK_ROOT.'vente/indexrestaurant'?>">Restaurant</a></li>
                                            <li><a href="<?=LINK_ROOT.'vente/indexlivre'?>">Livres de cuisine</a></li>
                                            <?php endif; ?>
                                            
                                        </ul> 
                                    </button>
                                </div> <!-- /#connection -->
                                <div class="panier col-md-6" id="panier">                                
                                    <?php if(!empty($_SESSION['user'])): ?> 
                                    <a class="btn btn-default lienPanier" href="<?=LINK_ROOT.'panier/indexpanier/'.$_SESSION['user']['id_user']?>">
                                        <span class="glyphicon glyphicon-shopping-cart"></span> 
                                        Votre Panier : 
                                        <div class="panierContent" id="panierContent">0 </div>
                                        articles
                                    </a>
                                    <?php else: ?>
                                        <a class="btn btn-default lienPanier" href="<?=LINK_ROOT.'vente/indexproduit/'?>"> Acheter des produits</a>
                                    <?php endif; ?>
                                </div>
                            </div> <!-- /.buttonNav-->
                        </div> <!-- /.row (.navbar-header) -->
                    
                    
                        <div class="row">
                            <div id="navbar" class="navbar-collapse collapse menuLiens">
                                <div class="containerMenuUl">
                                    <ul class="nav navbar-nav animSiteFadeInSlow">
                                        <li class="lienMenuChefDesFourneaux"><a href="<?=LINK_ROOT.'recette/index'?>">Categories</a></li>
                                        <li class="lienMenuChefDesFourneaux"><a href="<?=LINK_ROOT.'recette/indexchef'?>">Recettes de chef</a></li>
                                        <li class="lienMenuChefDesFourneaux"><a href="<?=LINK_ROOT.'recette/indexcategorie/3'?>">Forme et santé</a></li>
                                        <li class="lienMenuChefDesFourneaux"><a href="<?=LINK_ROOT.'error/enconstruction'?>">Livres</a></li>
                                        <li class="lienMenuChefDesFourneaux"><a href="<?=LINK_ROOT.'error/enconstruction'?>">Restaurants</a></li>
                                        <li class="lienMenuChefDesFourneaux"><a href="<?=LINK_ROOT.'vente/indexproduit'?>">Ustensiles de cuisine</a></li>
                                        <li class="lienMenuChefDesFourneaux"><a href="<?=LINK_ROOT.'error/enconstruction'?>">Vidéos</a></li>  
                                    </ul>
                                </div>
                            </div> <!-- /.menuLiens -->
                        </div> <!-- /.row -->
                    </div> <!-- /.container -->
                </div> <!-- /.containerNav -->
            </nav>
        </div> <!-- /.navbar-wrapper -->
    </div> <!-- /.menu -->
        

        <!-- Marketing messaging and featurettes
        ================================================== -->
        <div class="marketing">
            <div class="contentView" id="contentView">
                <!-- Input de recherche -->                
                <div class="animSiteShowFast input-group input-group-sm col-md-6 col-md-offset-3" id="wrapperSearchBar">
                    <span class="input-group-addon" id="loupe">
                        <span class="glyphicon glyphicon-search"></span>
                    </span>
                    <input class="form-control" type="text" list="dataListSearch" id="inputTextSearch" placeholder="Rechercher une recette..." style="font-style:italic;" aria-describedby="loupe" />
                    <datalist id="dataListSearch"></datalist>
                    <div id="divSearchResult"></div>   
                </div> <!-- /#wrapperSearchBar -->
                <?=$content_view?>
            </div>
            
        </div><!-- /.marketing -->
        <div id="row affiliation">
            <div class="col-md-4">
                <a href="#">
                    <img src="<?=IMG_LINK_ROOT?>affiliation/auchandrive.jpg" alt="utiliser auchan drive pour acheter vos ingrédients">
                </a>
            </div>
            <div class="col-md-4">
                <a href="#">
                    <img src="<?=IMG_LINK_ROOT?>affiliation/ecogourmet.png" alt="Eco gourmet">
                </a>
            </div>
            <div class="col-md-4">
                <a href="#">
                    <img src="<?=IMG_LINK_ROOT?>affiliation/plaisdesthes.jpg" alt="Plais du thé">
                </a>
            </div>
        </div> <!-- /.affiliation -->

        <!-- FOOTER -->
        <footer class="footer">
            <p>
                Chef des fourneaux est disponible sur Android 
                <a href="#"><img src="<?=IMG_LINK_ROOT?>icons/android128.png" alt="télécharger l'application android chef des fourneaux"></a>
            </p>
            <br>
            <p>
                Suivez-nous !!!
                <a href="https://www.facebook.com/pages/Chef-des-Fourneaux/791557667596027">
                    <img src="<?=IMG_LINK_ROOT?>icons/facebook128.png" alt="suivre chef des fourneaux sur facebook">
                </a>
                <a href="https://twitter.com/ChefdFourneaux"><img src="<?=IMG_LINK_ROOT?>icons/twitter128.png" alt="suivre chef des fourneaux sur twitter"></a>
                <a href="https://plus.google.com/u/0/b/116720301370410735975/116720301370410735975/about"><img src="<?=IMG_LINK_ROOT?>icons/google128.png" alt="suivre chef des fourneaux sur google +"></a>
                <a href="https://fr.pinterest.com/chefdfourneaux/"><img src="<?=IMG_LINK_ROOT?>icons/pinterest128.png" alt="suivre chef des fourneaux sur pinterest"></a>
                <a href="https://www.youtube.com/channel/UCgqEfUNcR0h94M6ioE76jtA"><img src="<?=IMG_LINK_ROOT?>icons/youtube128.png" alt="suivre chef des fourneaux sur youtube"></a>
            </p>
            <hr>
            <p>
                <a href="<?=LINK_ROOT?>">Retour à l'accueil</a>
            </p> 
            <p class="pull-right">
                <a href="#">Haut de page</a>
            </p>
            <p>
                <a href="#">Qui sommes nous&nbsp;?</a> - 
                <a href="#">Contact</a> - 
                <a href="#">Newsletter</a> - 
                <a href="#">Mentions légales</a> -  
                &copy; 2015 Chef des fourneaux
            </p>
        </footer>

        


        
        <canvas id="easteregg"></canvas>



        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script-->
        <script src="<?=WEB_ROOT?>js/bootstrap/bootstrap.min.js"></script>
        <script src="<?=WEB_ROOT?>js/bootstrap/docs.min.js"></script>
        <script src="<?=WEB_ROOT?>js/chefdesfourneaux.js"></script>


        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="<?=WEB_ROOT?>/js/bootstrap/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>