<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?=$pageTitle?></title>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Styles -->
        <link href="<?=WEB_ROOT?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?=WEB_ROOT?>/css/layouts/carousel.css" rel="stylesheet">
        <link href="<?=WEB_ROOT?>/css/chefdesfourneaux.css" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    </head>


    <body>
    <div class="row col-md-3 col-md-offset-3">
        <div class="panier" id="panier">
            Panier = 
            <div class="panierContent" id="panierContent">0</div>
        </div>
    </div>
        

        <!-- Marketing messaging and featurettes
        ================================================== -->

        <div class="container marketing">

            <?=$content_view?>
        
        


            <!-- FOOTER -->
            <footer>
            <p class="pull-right"><a href="#">Back to top</a></p>
            <p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
            </footer>

        </div><!-- /.container -->


        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script-->
        <script src="<?=WEB_ROOT?>js/bootstrap/bootstrap.min.js"></script>
        <script src="<?=WEB_ROOT?>js/bootstrap/docs.min.js"></script>
        <script src="<?=WEB_ROOT?>js/chefdesfourneaux.js"></script>


        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="<?=WEB_ROOT?>/js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>