<?=$tinyMCE?>
<?=$message?>


<form class="" method="post"  onsubmit="preparatif(); return false;" id="formRecette">
    <h2 class="form-signin-heading">
        <?=$pageTitle?>
    </h2>
    
    <table>
        <tr>
            <label for="titre">Titre de la recette que vous souhaitez ajouter : </label>
            <td><input type="text" name="titre" id="titre" required></td>
        </tr>
    </table>
    <br/>
    <textarea name="value" autofocus style="width: 50%;"></textarea>
    <br/>
    <table>
        <tr>
            <td><label for="id_cat">Catégorie : </label></td>
            <td>
                <select name="id_cat" id="id_cat">
                  <?php foreach ($categories as $categorie) {?>
                      <option value="<?=$categorie['id_cat']?>"><?=$categorie['value']?></option> 

                  <?php } ?>
                </select>
            </td>
        </tr>      



        <tr>
            <td><label for="tps_cuisson">Temps de cuisson : </label></td>
            <td><input type="text"  name="tps_cuisson" id="tps_cuisson" required></td>
        </tr>
        <tr>
            <td><label for="cout"></label></td>
            <td><input type="text"  name="cout" required /></td>
        </tr>
        <tr>
            <td><label for="difficulte">Difficulté : </label></td>
            <td>
                <select name="difficulte" id="difficulte">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </td>
        </tr>
        <tr>
            <td><label for="type">Type : </label></td>
            <td>
                <select name="type" id="type">
                    <option value="entrée">Entrée</option>
                    <option value="plat">Plat</option>
                    <option value="dessert">Dessert</option>
                </select> 
            </td>
        </tr>
    </table>


    <label for="diabete">diabete</label>
    <input type="checkbox" name="diabete" id="diabete" value="">

    <label for="ble">ble</label>
    <input type="checkbox" name="ble" id="ble" value="">

    <label for="lait">lait</label>
    <input type="checkbox" name="lait" id="lait" value="">

    <label for="oeuf">oeuf</label>
    <input type="checkbox" name="oeuf" id="oeuf" value="">

    <label for="arachide">arachide</label>
    <input type="checkbox" name="arachide" id="arachide" value="">

    <label for="soja">soja</label>
    <input type="checkbox" name="soja" id="soja" value="">

    <label for="gluten">gluten</label>
    <input type="checkbox" name="gluten" id="gluten" value="">


    <table  border="1">
        <tr><td collspan="4">Ingredients : </td></tr>
        <tr>
            <td></td>
            <td></td>
            <td>
                <select id="allunites"     style="min-width:150px;">
                  <?php foreach ($unites as $unite) {?>
                      <option value="<?=$unite['id_unite']?>" ><?=$unite['value']?></option> 
                  <?php } ?>
                </select>
            </td>
            <td>
                <input type="button" onclick="definirUnite();" value="definir" id="boutonunite">
            </td>
        </tr>      


        <tr>
            <td>
                    
                <select  id="allingredients" multiple size="8"   onclick="ajouterIngredient();"  style="min-width:150px;">
                  <?php foreach ($ingredients as $ingredient) {?>
                      <option value="<?=$ingredient['id_ingredient']?>" ><?=$ingredient['value']?></option> 
                  <?php } ?>
                </select>
                    
            </td>
            <td>
                <select id="ingredients"  name="ingredients[]" multiple size="8"   onclick="retirerIngredient();"  style="min-width:150px;">
                    
                </select>
            </td>

            <td>
                <select id="unites"  name="unites[]" multiple size="8" onclick="actualiserQuantite();"     style="min-width:150px;" onBlur="//masquer();" onFocus="afficher();">
                </select>    
            </td>
            <td>
                <input type="text" id="quantite">
                <input type="button" id="okquantite" onclick="definirQuantite();" value="ok">
            </td>
        </tr>

    </table>




    <input type="hidden"  name="id_livre"  value="1" style="min-width:150px;">
    <input type="hidden"  name="id_resto"  value="1">

    <BR>
    <button name="btn" class="btn btn-lg btn-primary" type="submit"><?=$pageTitle?></button><BR>
    <a href="<?=LINK_ROOT?>">Retour à l'accueil</a> - 

</form  style="min-width:150px;">


<script type="text/javascript">
    masquer();
</script>