<?=$tinyMCE?>
<?=$message?>
<script type="text/javascript">
    function ajouterIngredient(){
        var val=$( "#allingredients option:selected" ).val();
        var lab=$( "#allingredients option:selected" ).text();
        if($('#allingredients option').length!==0 ){
            $('#ingredients').append('<option value="'+val+'" selected="selected">'+lab+'</option>');
            $('#allingredients option:selected').remove();
        }
    }

    function retirerIngredient(){
        var val=$( "#ingredients option:selected" ).val();
        var lab=$( "#ingredients option:selected" ).text();
        if($('#ingredients option').length!==0 ){
            $('#allingredients').append('<option value="'+val+'" selected="selected">'+lab+'</option>');
            $('#ingredients option:selected').remove();
        }
    }

    function preparatif(){
        //selectionne tout
        $('#ingredients option').prop('selected', true);
    }

</script>




<form class="" method="post" border="1" onsubmit="preparatif();">
    <h2 class="form-signin-heading">
        <?=$pageTitle?>
    </h2>
    <textarea name="value" autofocus style="width: 100%;"></textarea>

    <table>
        <tr><td>categorie</td>
            <td>
                <select name="id_cat">
                  <?php foreach ($categories as $categorie) {?>
                      <option value="<?=$categorie['id_cat']?>"><?=$categorie['value']?></option> 

                  <?php } ?>
                </select>
            </td>
        </tr>      



        <tr>
            <td>temps de cuisson</td>
            <td><input type="text"  name="tps_cuisson"></td>
        </tr>
        <tr>
            <td>cout</td>
            <td><input type="text"  name="cout"  /></td>
        </tr>
        <tr>
            <td>difficulté</td>
            <td>
                <select name="difficulte">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>type</td>
            <td>
                <select name="type">
                    <option value="Entrée">Entrée</option>
                    <option value="Plat">Plat</option>
                    <option value="Dessert">Dessert</option>
                </select> 
            </td>
        </tr>
    </table>


    <label for="diabete">diabete</label>
    <input type="checkbox" name="diabete" id="diabete" value="">

    <label for="ble">ble</label>
    <input type="checkbox" name="ble" id="ble" value="">

    <label for="lait">lait</label>
    <input type="checkbox" name="lait" id="lait" value="">

    <label for="oeuf">oeuf</label>
    <input type="checkbox" name="oeuf" id="oeuf" value="">

    <label for="arachide">arachide</label>
    <input type="checkbox" name="arachide" id="arachide" value="">

    <label for="soja">soja</label>
    <input type="checkbox" name="soja" id="soja" value="">

    <label for="gluten">gluten</label>
    <input type="checkbox" name="gluten" id="gluten" value="">


    <table>
        <tr><td collspan="2">Ingredients</td></tr>
            <tr><td>
                
                <select  id="allingredients" multiple size="8"   onclick="ajouterIngredient();"  style="min-width:150px;">
                  <?php foreach ($ingredients as $ingredient) {?>
                      <option value="<?=$ingredient['id_ingredient']?>" ><?=$ingredient['value']?></option> 
                  <?php } ?>
                </select>
            </td>
            <td>
                <select id="ingredients"  name="ingredients[]" multiple size="8"   onclick="retirerIngredient();"  style="min-width:150px;">
                    
                </select>
            </td>

        </tr>      
    </table>




    <input type="hidden"  name="id_livre"  value="1"m  style="min-width:150px;">
    <input type="hidden"  name="id_resto"  value="1">

    <BR>
    <button name="btn" class="btn btn-lg btn-primary" type="submit"><?=$pageTitle?></button><BR>
    <a href="<?=LINK_ROOT?>">Retour à l'accueil</a> - 

</form  style="min-width:150px;">