<?=$urlWebService?>
<?=$message?>
<link rel="stylesheet" type="text/css" href="css/graph.css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript" src="scripts/filtreJs.js"></script>



<form class="" method="post"  onsubmit="" id="formRecette">
    <h2 class="form-signin-heading">
        <?=$pageTitle?>
    </h2>


    <div>
        <label for="categories">Catégories : </label>
        <select name="categories[]" id="categories" multiple>
          <?php foreach ($categories as $categorie) {?>
              <option value="<?=$categorie['id_cat']?>"><?=$categorie['value']?></option> 
          <?php } ?>
        </select>

        <div id="divChoixCat" >
            <input type="button" id="btnCatAjouter" value="Ajouter" >
            <input type="button" id="btnCatModifier" value="Modifier" >
            <input type="button" id="btnCatSupprimer" value="Supprimer" >

              <div id="divCat" >
                  <input type="text" id="textCatAjouter" value="" >
                  <input type="text" id="textCatModifier" value="" >
                  
                  
                  <input type="button" id="btnCatValider" value="OK">
                  <!--input type="button" id="btnCatCancel" value="Annuler"-->
              </div>            
            
        </div>

    </div>


    <div>
        <label for="ingredients">Ingrédients : </label>
        <select name="ingredients[]"  id="ingredients"     style="min-width:150px;" multiple>
          <?php foreach ($ingredients as $ingredient) {?>
              <option value="<?=$ingredient['id_ingredient']?>" ><?=$ingredient['value']?></option> 
          <?php } ?>
        </select>

        <div id="divIng" >
            <input type="text" id="inputIng">
            <input type="button" id="btnIng">
        </div>
    </div>


    <div>
        <label for="unites">Unités : </label>
        <select name="unites[]" id="unites"     style="min-width:150px;" multiple>
          <?php foreach ($unites as $unite) {?>
              <option value="<?=$unite['id_unite']?>" ><?=$unite['value']?></option> 
          <?php } ?>
        </select>

        <div  id="divUnit" >
            <input type="text" id="inputUnit">
            <input type="button" id="btnUnit">
        </div>

    </div>



</form  style="min-width:150px;">


