<?=$urlWebService?>
<?=$message?>




<form class="" method="post"  onsubmit="" id="formRecette">
    <h2 class="form-signin-heading">
        <?=$pageTitle?>
    </h2>


    <div>
        <label for="categories">Catégories : </label>
        <select name="categories[]" id="categories" multiple>
          <?php foreach ($categories as $categorie) {?>
              <option value="<?=$categorie['id_cat']?>"><?=$categorie['value']?></option> 
          <?php } ?>
        </select>

        <div id="
        " >
            <input type="button" id="btnCatAjouter" value="Ajouter" >
            <input type="button" id="btnCatModifier" value="Modifier" >
            <input type="button" id="btnCatSupprimer" value="Supprimer" >

              <div id="divCat" >
                  <input type="text" id="textCatAjouter" value="" >
                  <input type="text" id="textCatModifier" value="" >
                  
                  
                  <input type="button" id="btnCatValider" value="OK">
                  <!--input type="button" id="btnCatCancel" value="Annuler"-->
              </div>            
            
        </div>

    </div>

    <!-- INgredients -->
    <div>
        <label for="ingredients">Ingrédients : </label>
        <select name="ingredients[]" id="ingredients" multiple>
          <?php foreach ($ingredients as $ingredient) {?>
              <option value="<?=$ingredient['id_ingredient']?>"><?=$ingredient['value']?></option> 
          <?php } ?>
        </select>

        <div id="divChoixIng" >
            <input type="button" id="btnIngAjouter" value="Ajouter" >
            <input type="button" id="btnIngModifier" value="Modifier" >
            <input type="button" id="btnIngSupprimer" value="Supprimer" >

              <div id="divIng" >
                  <input type="text" id="textIngAjouter" value="" >
                  <input type="text" id="textIngModifier" value="" >
                  
                  
                  <input type="button" id="btnIngValider" value="OK">
                  <!--input type="button" id="btnCatCancel" value="Annuler"-->
              </div>            
            
        </div>

    </div>


 




    <!-- Unité -->
    <div>
        <label for="unites">Unités : </label>
        <select name="unites[]" id="unites" multiple>
          <?php foreach ($unites as $unite) {?>
              <option value="<?=$unite['id_unite']?>"><?=$unite['value']?></option> 
          <?php } ?>
        </select>

        <div id="divChoixUnit" >
            <input type="button" id="btnUnitAjouter" value="Ajouter" >
            <input type="button" id="btnUnitModifier" value="Modifier" >
            <input type="button" id="btnUnitSupprimer" value="Supprimer" >

              <div id="divUnit" >
                  <input type="text" id="textUnitAjouter" value="" >
                  <input type="text" id="textUnitModifier" value="" >
                  
                  
                  <input type="button" id="btnUnitValider" value="OK">
                  <!--input type="button" id="btnCatCancel" value="Annuler"-->
              </div>            
            
        </div>

    </div>



</form  style="min-width:150px;">


