<?php
//var_dump($recettes[0]['ingredients']);
//var_dump($recettes);
?>
<div class="container containerView">
    <div class="blog-header">
        <h1 class="blog-title">Page d'administration du site</h1>
    </div>

    <div class="row">
        <div class="col-sm-8 blog-main">
            <a type="button" class="btn btn-primary" href="<?=LINK_ROOT.'admin/creerrecette'?>">Ajouter une Recette</a>
            <a type="button" class="btn btn-primary" href="<?=LINK_ROOT.'admin/gestion'?>">Gérer les catégories, ingrédients et unités</a>
            <table class="table table-bordered">
                <tr>
                    <th colspan=2 style="text-align: center"><h1>Recettes</h1></th>
                </tr>
                <?php if(!empty($recettes)): foreach($recettes as $recette): ?>
                <tr>
                    <td style="text-align: center"><p><?=$recette['titre']?></p></td>
                    <td style="text-align: center">
                        <a type="button" class="btn btn-warning" href="<?=LINK_ROOT.'recette/categorie/'.$recette['slugtitre']?>">Afficher</a>
                        <a type="button" class="btn btn-success" href="<?=LINK_ROOT.'admin/mettreajourrecette/'.$recette['id_recette']?>">Mettre à jour</a>
                        <a type="button" class="btn btn-info" href="<?=LINK_ROOT.'adminproduit/lierproduit/'.$recette['id_recette']?>">Associer à des produits</a>
                        <a type="button" class="btn btn-danger" href="<?=LINK_ROOT.'admin/supprimerrecette/'.$recette['id_recette']?>">Supprimer</a>
                          
                    </td>
                </tr>
                <?php endforeach; ?>
                <?php endif; ?>

            </table>
            
        </div><!-- /.blog-main -->

    </div><!-- /.row -->

</div><!-- /.container -->