<?=$tinyMCE?>
<?php
//$message

var_dump($viewrecette);
?>
<script type="text/javascript">

    tabUnit  = new Array();
    tabQuant = new Array();
    

    function ajouterIngredient(){
        var val=$( "#allingredients option:selected" ).val();
        var lab=$( "#allingredients option:selected" ).text();
        if($('#allingredients option').length!==0 ){
            $('#ingredients').append('<option value="'+val+'" selected="selected">'+lab+'</option>');
            $('#unites').append('<option value="'+val+'" selected="selected">...</option>');

            $('#allingredients option:selected').remove();

            tabUnit.push(1);
            tabQuant.push(1);
            console.log(tabUnit+ "  ## "+tabQuant);

        }
    }

    function retirerIngredient(){
        var val=$( "#ingredients option:selected" ).val();
        var lab=$( "#ingredients option:selected" ).text();
        if($('#ingredients option').length!==0 ){

            //$('#unites option:eq(3)').prop('selected', true);
            var ing =document.getElementById("ingredients");
            var unit =document.getElementById("unites");

            //supprime fna le select
            unit.options[ing.selectedIndex].remove();
            
            //supprime dans quantité
            tabUnit.splice(ing.selectedIndex,1);
            tabQuant.splice(ing.selectedIndex,1);

            console.log(tabUnit +" # "+ tabQuant);

            $('#allingredients').append('<option value="'+val+'" selected="selected">'+lab+'</option>');
            $('#ingredients option:selected').remove();
        }
    }


    function definirUnite(){
        var allUnit = document.getElementById("allunites");
        var unit = document.getElementById("unites");
        if(unit.selectedIndex>=0 ){
            unit.options[unit.selectedIndex].value= allUnit.options[allUnit.selectedIndex].value ;
            unit.options[unit.selectedIndex].text= "1 " + allUnit.options[allUnit.selectedIndex].text ;

            tabUnit[unit.selectedIndex]=allUnit.options[allUnit.selectedIndex].text;
            tabQuant[unit.selectedIndex]=1;

            console.log(tabUnit+"##"+ tabQuant);
            //alert(allUnit.options[allUnit.selectedIndex].text); 
        }
    }

    function definirQuantite(){

        var quant = document.getElementById("quantite");
        var unit = document.getElementById("unites");
        if(parseFloat(quant.value)>0 ){
            
            unit.options[unit.selectedIndex].text= parseFloat(quant.value) + " " + tabUnit[unit.selectedIndex];

            tabQuant[unit.selectedIndex]=quant.value;
            console.log(tabUnit+"##"+ tabQuant);

            //alert(allUnit.options[allUnit.selectedIndex].text); 
        }



    }

    function preparatif(){
        //selectionne tout
        $('#ingredients option').prop('selected', true);
        $('#unites option').prop('selected', true);





        var formulaire = document.getElementById("formRecette");
                    
        
         var inputQuant;

        for(i=0; i<tabQuant.length; i++){
            inputQuant = document.createElement("input");

            inputQuant.setAttribute("type","hidden");
            inputQuant.setAttribute("name","quantites["+i+"]");
            inputQuant.setAttribute("value",tabQuant[i]);
            formulaire.appendChild(inputQuant);
        }





         
        formulaire.submit();

    }



    function actualiserQuantite(){
     var quant = document.getElementById("quantite");
     quant.value=tabQuant[document.getElementById("unites").selectedIndex];
    }



    function masquer(){

        document.getElementById("boutonunite").style.visibility='hidden';
        document.getElementById("allunites").style.visibility='hidden';
        document.getElementById("quantite").style.visibility='hidden';
        document.getElementById("okquantite").style.visibility='hidden';
    }


    function afficher(){
        document.getElementById("boutonunite").style.visibility='visible';
        document.getElementById("allunites").style.visibility='visible';
        document.getElementById("quantite").style.visibility='visible';
        document.getElementById("okquantite").style.visibility='visible';
    }





</script>




<form class="" method="post"  onsubmit="preparatif();" id="formRecette">
    <h2 class="form-signin-heading">
        <?=$pageTitle?>
    </h2>
    <textarea name="value" autofocus style="width: 100%;"><?=$viewrecette['value']?></textarea>

    <table>
        <tr><td>categorie</td>
            <td>
                <select name="id_cat">
                  <?php foreach ($categories as $categorie) {
                        if($categorie['value'] == $viewrecette['categorie'] ){
                            $txt=" selected ";
                        }else{
                            $txt="";
                        }
                   ?>
                      <option value="<?=$categorie['id_cat']?>"  <?=$txt?> ><?=$categorie['value']?></option> 

                  <?php } ?>
                </select>
            </td>
        </tr>      



        <tr>
            <td>temps de cuisson</td>
            <td><input type="text"  name="tps_cuisson"  value="<?=$viewrecette['tps_cuisson']?>" ></td>
        </tr>
        <tr>
            <td>cout</td>
            <td><input type="text"  name="cout"   value=""  /></td>
        </tr>
        <tr>
            <td>difficulté</td>
            <td>
                <select name="difficulte">
                    <?php
                    for ($i=1; $i < 6; $i++) { 
                        if($i== $viewrecette['difficulte'] ){
                            $txt=" selected ";
                        }else{
                            $txt="";
                        }
                        echo "<option value='$i' $txt >$i</option>";
                     } 
                    
                   ?>
                </select>
            </td>
        </tr>
        <tr>
            <td>type</td>
            <td>
                <select name="type">
                    <?php

                        if($viewrecette['type']=="entrée" ){
                            $txt1=" selected "; $txt2=""; $txt3="";
                        }elseif($viewrecette['type']=="plat"){
                            $txt1=""; $txt2=" selected "; $txt3="";
                        }else{
                            $txt1=""; $txt2=""; $txt3=" selected ";
                        }
                   ?>
                    <option value="Entrée" <?=$txt1?> >Entrée</option>
                    <option value="Plat"  <?=$txt2?> >Plat</option>
                    <option value="Dessert"  <?=$txt3?> >Dessert</option>
                </select> 
            </td>
        </tr>
    </table>


    <?php


        $diabete=($viewrecette['diabete']?" checked ":"");
        $ble=($viewrecette['ble']?" checked ":"");
        $lait=($viewrecette['lait']?" checked ":"");
        $oeuf=($viewrecette['oeuf']?" checked ":"");
        $arachide=($viewrecette['arachide']?" checked ":"");
        $soja=($viewrecette['soja']?" checked ":"");
        $gluten=($viewrecette['gluten']?" checked ":"");

    ?>
    <label for="diabete">diabete</label>
    <input type="checkbox" name="diabete" id="diabete" value="0" <?=$diabete?> >

    <label for="ble">ble</label>
    <input type="checkbox" name="ble" id="ble" value="1" <?=$ble?> >

    <label for="lait">lait</label>
    <input type="checkbox" name="lait" id="lait" value="0" <?=$lait?> >

    <label for="oeuf">oeuf</label>
    <input type="checkbox" name="oeuf" id="oeuf" value="0" <?=$oeuf?> >

    <label for="arachide">arachide</label>
    <input type="checkbox" name="arachide" id="arachide" value="0" <?=$arachide?> >

    <label for="soja">soja</label>
    <input type="checkbox" name="soja" id="soja" value="0" <?=$soja?> >

    <label for="gluten">gluten</label>
    <input type="checkbox" name="gluten" id="gluten" value="0" <?=$gluten?> >


    <table  border="0">
        <tr><td collspan="4">Ingredients</td></tr>
            <tr><td>
            </td>
            <td>
            </td>
            <td>
                <select id="allunites"     style="min-width:150px;">
                  <?php foreach ($unites as $unite) {?>
                      <option value="<?=$unite['id_unite']?>" ><?=$unite['value']?></option> 
                  <?php } ?>
                </select>
            </td>
            <td>
                <input type="button" onclick="definirUnite();" value="definir" id="boutonunite">
            </td>

        </tr>      


        <tr>
            <td>
                    
                <select  id="allingredients" multiple size="8"   onclick="ajouterIngredient();"  style="min-width:150px;">
                  <?php
                  //var_dump($ingredients);
                  foreach ($ingredients as $ingredient) {
                    //echo "assssssssssss";
                    echo "<option value='".$ingredient['id_ingredient']."' >".$ingredient['value']."</option>";
                  }



                  ?>
                </select>
                    
            </td>
            <td>
                <select id="ingredients"  name="ingredients[]" multiple size="8"   onclick="retirerIngredient();"  style="min-width:150px;">
                    
                </select>
            </td>

            <td>
                <select id="unites"  name="unites[]" multiple size="8" onclick="actualiserQuantite();"     style="min-width:150px;" onBlur="//masquer();" onFocus="afficher();">
                </select>    
            </td>
            <td>
                <input type="text" id="quantite">
                <input type="button" id="okquantite" onclick="definirQuantite();" value="ok">
            </td>
        </tr>

    </table>




    <input type="hidden"  name="id_livre"  value="1"m  style="min-width:150px;">
    <input type="hidden"  name="id_resto"  value="1">

    <BR>
    <button name="btn" class="btn btn-lg btn-primary" type="submit"><?=$pageTitle?></button><BR>
    <a href="<?=LINK_ROOT?>">Retour à l'accueil</a> - 

</form  style="min-width:150px;">


<script type="text/javascript">
    masquer();
</script>