<?=$tinyMCE?>
<?=$message?>
<?php


var_dump("skhlkmhfhdh",$viewrecette);




?>
<script type="text/javascript">




</script>




<form class="" method="post"  onsubmit="preparatif();" id="formRecette">
    <h2 class="form-signin-heading">
        <?=$pageTitle?>
    </h2>
    <textarea name="value" autofocus style="width: 100%;"><?=$viewrecette['value']?></textarea>

    <table>
        <tr><td>categorie</td>
            <td>
                <select name="id_cat">
                  <?php foreach ($categories as $categorie) {
                        if($categorie['value'] == $viewrecette['categorie'] ){
                            $txt=" selected ";
                        }else{
                            $txt="";
                        }
                   ?>
                      <option value="<?=$categorie['id_cat']?>"  <?=$txt?> ><?=$categorie['value']?></option> 

                  <?php } ?>
                </select>
            </td>
        </tr>      



        <tr>
            <td>temps de cuisson</td>
            <td><input type="text"  name="tps_cuisson"  value="<?=$viewrecette['tps_cuisson']?>" ></td>
        </tr>
        <tr>
            <td>cout</td>
            <td><input type="text"  name="cout"   value=""  /></td>
        </tr>
        <tr>
            <td>difficulté</td>
            <td>
                <select name="difficulte">
                    <?php
                    for ($i=1; $i < 6; $i++) { 
                        if($i== $viewrecette['difficulte'] ){
                            $txt=" selected ";
                        }else{
                            $txt="";
                        }
                        echo "<option value='$i' $txt >$i</option>";
                     } 
                    
                   ?>
                </select>
            </td>
        </tr>
        <tr>
            <td>type</td>
            <td>
                <select name="type">
                    <?php

                        if($viewrecette['type']=="entrée" ){
                            $txt1=" selected "; $txt2=""; $txt3="";
                        }elseif($viewrecette['type']=="plat"){
                            $txt1=""; $txt2=" selected "; $txt3="";
                        }else{
                            $txt1=""; $txt2=""; $txt3=" selected ";
                        }
                   ?>
                    <option value="Entrée" <?=$txt1?> >Entrée</option>
                    <option value="Plat"  <?=$txt2?> >Plat</option>
                    <option value="Dessert"  <?=$txt3?> >Dessert</option>
                </select> 
            </td>
        </tr>
    </table>


    <?php


        $diabete=($viewrecette['diabete']?" checked ":"");
        $ble=($viewrecette['ble']?" checked ":"");
        $lait=($viewrecette['lait']?" checked ":"");
        $oeuf=($viewrecette['oeuf']?" checked ":"");
        $arachide=($viewrecette['arachide']?" checked ":"");
        $soja=($viewrecette['soja']?" checked ":"");
        $gluten=($viewrecette['gluten']?" checked ":"");

    ?>
    <label for="diabete">diabete</label>
    <input type="checkbox" name="diabete" id="diabete" value="0" <?=$diabete?> >

    <label for="ble">ble</label>
    <input type="checkbox" name="ble" id="ble" value="1" <?=$ble?> >

    <label for="lait">lait</label>
    <input type="checkbox" name="lait" id="lait" value="0" <?=$lait?> >

    <label for="oeuf">oeuf</label>
    <input type="checkbox" name="oeuf" id="oeuf" value="0" <?=$oeuf?> >

    <label for="arachide">arachide</label>
    <input type="checkbox" name="arachide" id="arachide" value="0" <?=$arachide?> >

    <label for="soja">soja</label>
    <input type="checkbox" name="soja" id="soja" value="0" <?=$soja?> >

    <label for="gluten">gluten</label>
    <input type="checkbox" name="gluten" id="gluten" value="0" <?=$gluten?> >


    <table  border="0">
        <tr><td collspan="4">Ingredients</td></tr>
            <tr><td>
            </td>
            <td>
            </td>
            <td>
                <select id="allunites"     style="min-width:150px;">
                  <?php foreach ($unites as $unite) {?>
                      <option value="<?=$unite['id_unite']?>" ><?=$unite['value']?></option> 
                  <?php } ?>
                </select>
            </td>
            <td>
                <input type="button" onclick="definirUnite();" value="definir" id="boutonunite">
            </td>

        </tr>      


        <tr>
            <td>
                    
                <select  id="allingredients" multiple size="8"   onclick="ajouterIngredient();"  style="min-width:150px;">
                  <?php
                  
                  function ingredientIsUsed( $id, $tabIng ){

                    foreach ($tabIng as  $ing) {

                        if ($ing['id_ingredient']===$id) {
                            return true;
                        }
                    }
                    return false;
                  }


                  foreach ($ingredients as $ingredient) {
                     var_dump($ingredient);
                    if( !ingredientIsUsed( $ingredient['id_ingredient'], $viewrecette['ingredients'] ) ){
                        echo "<option value='".$ingredient['id_ingredient']."' >".$ingredient['value']."</option>";
                    }
                  }



                  ?>
                </select>
                    
            </td>
            <td>
                
                <select id="ingredients"  name="ingredients[]" multiple size="8"   onclick="retirerIngredient();"  style="min-width:150px;">
                <?php

                  foreach ($viewrecette['ingredients'] as $ingredient) {
                    echo "<option value='".$ingredient['id_ingredient']."' >".$ingredient['ingredients']."</option>";
                  }


                ?>
                </select>
            </td>

            <td>
                <select id="unites"  name="unites[]" multiple size="8" onclick="actualiserQuantite();"     style="min-width:150px;" onBlur="" onFocus="afficher();">
                </select>    
            </td>
            <td>
                <input type="text" id="quantite">
                <input type="button" id="okquantite" onclick="definirQuantite();" value="ok">
            </td>
        </tr>

    </table>




    <input type="hidden"  name="id_livre"  value="1">
    <input type="hidden"  name="id_resto"  value="1">

    <BR>
    <button name="btn" class="btn btn-lg btn-primary" type="submit"><?=$pageTitle?></button><BR>
    <a href="<?=LINK_ROOT?>">Retour à l'accueil</a> - 

</form style="min-width: 150px;">

    <script src="<?=WEB_ROOT?>/js/script.js"></script>

<script type="text/javascript">
    //masquer();

<?php
//ici pour que les elements soient deja crées

    $strTabUnit="tabUnit  = new Array(";
    $strTabQuant="tabQuant  = new Array(";
    $alors=false;
    $js="";
    foreach ($viewrecette['ingredients'] as $ingredient) {
        $strTabUnit.="'".$ingredient['unite']."', ";
        $strTabQuant.=$ingredient['value'].", ";
        
        //$ingredients
        
        $js.="$('#unites').append('<option value=\"".$ingredient['id_unite']."\" selected >".$ingredient['value'].' '.$ingredient['unite']."</option>');\n   ";

        $alors=true;
    }
    if($alors){
        $strTabUnit=substr($strTabUnit, 0, -2);
        $strTabQuant=substr($strTabQuant, 0, -2);
    }
    $strTabUnit.=");\n";
    $strTabQuant.=");\n";


    echo $strTabUnit; 
    echo $strTabQuant; 
    echo $js;
    

?>
console.log(tabUnit +" # "+ tabQuant);

</script>