<?=$message?>

<div class="container">
    <div class="blog-header">
        <h1 class="blog-title">Suppression de recette</h1>
    </div>

    <div class="row">
        <div class="col-sm-8 blog-main">
        	<form method="post">
        		<input type="hidden" name="idrecette" value="<?=$idRecette?>" class="btn btn-lg btn-primary" >
        		<button name="btn" class="btn btn-lg btn-primary" type="submit" >Supprimer la recette</button>
            

        </div><!-- /.blog-main -->

    </div><!-- /.row -->

</div><!-- /.container -->