<!-- Carousel
        ================================================== -->
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="<?=WEB_ROOT?>/img/entree.jpg" alt="First slide">
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>L'eau à la bouche?</h1>
                            <p><a class="btn btn-lg btn-primary" href="<?=LINK_ROOT.'user/inscription'?>" role="button">Inscription</a></p>
                        </div> <!-- /.carousel-caption -->
                    </div> <!-- /.container -->
                </div> <!-- /.item -->
                <div class="item">
                    <img src="<?=WEB_ROOT?>/img/plat.jpg" alt="Second slide">
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>Envie de plus de recettes?</h1>
                            <p><a class="btn btn-lg btn-primary" href="<?=LINK_ROOT.'recette/index'?>" role="button">Voir toutes les recettes</a></p>
                        </div> <!-- /.carousel-caption -->
                    </div> <!-- /.container -->
                </div> <!-- /.item -->
                <div class="item">
                    <img src="<?=WEB_ROOT?>/img/dessert.jpg" alt="Third slide">
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>Bon appétit ! </h1>
                            <p><a class="btn btn-lg btn-primary" href="<?=LINK_ROOT.'recette/chef'?>" role="button">Voir les recettes de nos chefs</a></p>
                        </div> <!-- /.carousel-caption -->
                    </div> <!-- /.container -->
                </div> <!-- /.item -->
                <div class="item">
                    <img src="<?=WEB_ROOT?>/img/dessert.jpg" alt="Third slide">
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>Bon appétit ! </h1>
                            <p><a class="btn btn-lg btn-primary" href="<?=LINK_ROOT.'recette/chef'?>" role="button">Voir les recettes de nos chefs</a></p>
                        </div> <!-- /.carousel-caption -->
                    </div> <!-- /.container -->
                </div> <!-- /.item -->
            </div> <!-- /.carousel-inner -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Précédent</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Suivant</span>
            </a>
        </div><!-- /.carousel -->

<!-- Doit être automatisé avec les différentes catégories et les chefs (tables catégories et table restaurant...) -->

<hr/>
<!-- Entrées / Plats / Desserts -->
<div class="row">
    <div class="col-lg-4">
        <img class="img-circle" src="<?=WEB_ROOT?>/img/entree2.jpg" alt="Generic placeholder image" style="width: 140px; height: 140px;">
        <h2>Cuisine du monde / entrée</h2>
        <p>Trouver des trucs à raconter sur les entrées, je laisse ça aux poètes</p>
        <p><a class="btn btn-default" href="#" role="button">Voir toutes les entrées &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <img class="img-circle" src="<?=WEB_ROOT?>/img/plat1.jpg" alt="Generic placeholder image" style="width: 140px; height: 140px;">
        <h2>Authentique / plats</h2>
        <p>Trouver des trucs à raconter sur les plats</p>
        <p><a class="btn btn-default" href="#" role="button">Voir tous les plats &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <img class="img-circle" src="<?=WEB_ROOT?>/img/dessert2.jpg" alt="Generic placeholder image" style="width: 140px; height: 140px;">
        <h2>Santé / Dessert</h2>
        <p>Trouver des trucs à raconter sur les desserts</p>
        <p><a class="btn btn-default" href="#" role="button">Voir tous les desserts &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
</div><!-- /.row -->

<hr/>
<!-- Recettes des chefs -->
<div class="row">
    <div class="col-lg-4">
        <img class="img-circle" src="<?=WEB_ROOT?>/img/entree2.jpg" alt="Generic placeholder image" style="width: 140px; height: 140px;">
        <h2>Chef 1</h2>
        <p></p>
        <p><a class="btn btn-default" href="#" role="button">Voir toutes les entrées &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <img class="img-circle" src="<?=WEB_ROOT?>/img/plat1.jpg" alt="Generic placeholder image" style="width: 140px; height: 140px;">
        <h2>Chef 2</h2>
        <p>Trouver des trucs à raconter sur les plats</p>
        <p><a class="btn btn-default" href="#" role="button">Voir tous les plats &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <img class="img-circle" src="<?=WEB_ROOT?>/img/dessert2.jpg" alt="Generic placeholder image" style="width: 140px; height: 140px;">
        <h2>Chef 3</h2>
        <p>Trouver des trucs à raconter sur les desserts</p>
        <p><a class="btn btn-default" href="#" role="button">Voir tous les desserts &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
</div><!-- /.row -->

