<!-- Carousel ================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
<!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="<?=IMG_LINK_ROOT?>cupckeschocolateblancfraise.png" alt="cupcake fraise, recette de cuisine">
            <div class="container">
                <div class="carousel-caption">
                    <h2>L'eau à la bouche?</h2>
                    <p><a class="btn btn-lg btn-primary" href="<?=LINK_ROOT.'user/inscription'?>" role="button">Inscription</a></p>
                </div> <!-- /.carousel-caption -->
            </div> <!-- /.container -->
        </div> <!-- /.item -->

        <!-- Affiche l'image de la recette ayant le top 1 en base -->
        <div class="item">
        <?php foreach($recettes as $recette): ?>

            <?php if($recette['top'] == 1): ?>
            <img src="<?=IMG_LINK_ROOT.$recette['img']?>" alt="<?=$recette['titre']?>">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Envie de plus de recettes?</h1>
                    <p><a class="btn btn-lg btn-primary" href="<?=LINK_ROOT.'recette/categorie/'.$recette['slugtitre']?>" role="button">Voir cette recette</a></p>
                </div> <!-- /.carousel-caption -->
            </div> <!-- /.container -->
        <?php endif; endforeach; ?>
        </div> <!-- /.item -->

        <!-- Affiche l'image de la recette ayant le top 2 en base -->
        <div class="item">
        <?php foreach($recettes as $recette): ?>
            <?php if($recette['top'] == 2): ?>
            <img src="<?=IMG_LINK_ROOT.$recette['img']?>" alt="<?=$recette['titre']?>">
            <div class="container">
                <div class="carousel-caption">
                    <h2>Voulez vous consulter cette recette ?</h2>
                    <p><a class="btn btn-lg btn-primary" href="<?=LINK_ROOT.'recette/categorie/'.$recette['slugtitre']?>" role="button">Voir cette recette</a></p>
                </div> <!-- /.carousel-caption -->
            </div> <!-- /.container -->
        <?php endif; endforeach; ?>
        </div> <!-- /.item -->

        <!-- Affiche l'image de la recette ayant le top 3 en base -->
        <div class="item">
        <?php foreach($recettes as $recette): ?>
            <?php if($recette['top'] == 3): ?>
            <img src="<?=IMG_LINK_ROOT.$recette['img']?>" alt="<?=$recette['titre']?>">
            <div class="container">
                <div class="carousel-caption">
                    <h2>Envie de plus de recettes ?</h2>
                    <p><a class="btn btn-lg btn-primary" href="<?=LINK_ROOT.'recette/categorie/'.$recette['slugtitre']?>" role="button">Voir cette recette</a></p>
                </div> <!-- /.carousel-caption -->

            </div> <!-- /.container -->
        <?php endif; endforeach; ?>
        </div> <!-- /.item -->
    </div> <!-- /.carousel-inner -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Précédent</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Suivant</span>
    </a>
</div><!-- /.carousel -->

<div class="containerViewIndex">
    <div class="container containerView">

        <div class="row textHoverImg">
            <strong>
                <h3>Vous trouverez ici nos meilleures recettes de chef, 
                    <p>ainsi que des recettes de grands livres de cuisine afin ne pas rater vos plats</p>
                </h3>
            </strong>
        </div>

        <!-- Entrées / Plats / Desserts -->
        <div class="row">
            <!-- Entrée -->
            <div class="col-lg-4">
                <a href="<?=LINK_ROOT.'recette/type/entrée'?>">
                    <img class="img-circle" src="<?=WEB_ROOT?>/img/type/entrée.jpg" alt="entrée, chef des fourneaux">
                </a>
                <h3>Entrée</h3>
            </div><!-- /.col-lg-4 -->
            <!-- Plat -->
            <div class="col-lg-4">
                <a href="<?=LINK_ROOT.'recette/type/plat'?>">
                    <img class="img-circle" src="<?=WEB_ROOT?>/img/type/plat.jpg" alt="plat, chef des fourneaux">
                </a>
                <h3>Plats</h3>
            </div><!-- /.col-lg-4 -->
            <!-- Dessert -->
            <div class="col-lg-4">
                <a href="<?=LINK_ROOT.'recette/type/dessert'?>">
                    <img class="img-circle" src="<?=WEB_ROOT?>/img/type/dessert.jpg" alt="dessert, chef des fourneaux">
                </a>
                <h3>Desserts</h3>    
            </div><!-- /.col-lg-4 -->

            <div class="legendeImg">
                <h3>Les tops recettes du mois, tartines fêta tomates, recettes de sushis et makis.</h3>
            </div>
        </div><!-- /.row -->
        <hr/>
        
        <!-- Recettes du moment -->
        <div class="row">
            <!-- Entrée -->
            <div class="col-lg-4">
                <a href="<?=LINK_ROOT.'recette/categorie/tartine-feta-tomates'?>">
                    <img class="img-circle" src="<?=IMG_LINK_ROOT.'top/tartinefetatomate.png'?>" alt="Tartine fêta tomates">
                </a>
                <h3>Entrée</h3>
            </div><!-- /.col-lg-4 -->
            <!-- Plat -->
            <div class="col-lg-4">
                <a href="<?=LINK_ROOT.'recette/categorie/maki-sushi-japonnais'?>">
                    <img class="img-circle" src="<?=IMG_LINK_ROOT.'top/makishuchijaponais.png'?>" alt="MAki sushi japonais">
                </a>
                <h3>Plats</h3>
            </div><!-- /.col-lg-4 -->
            <!-- Dessert -->
            <div class="col-lg-4">
                <a href="<?=IMG_LINK_ROOT.'top/muffinalacanelle.png'?>">
                    <img class="img-circle" src="<?=IMG_LINK_ROOT.'top/muffinalacanelle.png'?>" alt="Muffin à la cannelle">
                </a>
                <h3>Desserts</h3>    
            </div><!-- /.col-lg-4 -->
            <div class="legendeImg">
                <h3>C'est bientôt l'été, le temps des régimes ! Faites vous plaisir en gardant la ligne avec nos recettes minceurs !</h3>
            </div>
        </div><!-- /.row -->
        <hr/>

        <!-- Chefs du moment -->
        <div class="row">
            <!-- Entrée -->
            <div class="col-lg-4">
                <a href="#">
                    <img class="img-circle" src="<?=IMG_LINK_ROOT.'chef/milanpesek.jpg'?>" alt="Milan peseck">
                </a>
                <h3>Milen Pesek</h3>
            </div><!-- /.col-lg-4 -->
            <!-- Plat -->
            <div class="col-lg-4">
                <a href="#">
                    <img class="img-circle" src="<?=IMG_LINK_ROOT.'chef/angelleon.png'?>" alt="plat, chef des fourneaux">
                </a>
                <h3>Angel Leon</h3>
            </div><!-- /.col-lg-4 -->
            <!-- Dessert -->
            <div class="col-lg-4">
                <a href="#">
                    <img class="img-circle" src="<?=IMG_LINK_ROOT.'chef/sebastien-zozaya.jpg'?>" alt="Sebastien ZOzoya">
                </a>
                <h3>Sébastien Zozoya</h3>    
            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
    </div><!-- /.container -->

    <img class="img-responsive" src="<?=IMG_LINK_ROOT?>produit/1600imgproduits.png" alt="acheter nos ustensiles de cuisines semi-pro">

    <div class="container containerView">
        <div class="row textHoverImg">
            <strong>
                <h3>Devenez un vrai chef cuisinier chez vous ! 
                    <p>Découvrez nos produits professionnels pour faire vos recettes parfaitement</p>
                </h3>
            </strong>
        </div>
        <!-- Produits du moment -->
        <div class="row">
            <?php foreach($produits as $produit): ?>
                <?php if($produit['top'] == 1): ?>
                    <div class="col-lg-4">
                        <a href="<?=LINK_ROOT.'vente/produit/'.$produit['id_produit']?>">
                            <img class="img-circle" src="<?=IMG_LINK_ROOT.$produit['img']?>" alt="<?= $produit['value']?>">
                        </a>
                        <h3><?= $produit['value']?></h3>
                    </div><!-- /.col-lg-4 -->
                <?php endif; ?>
                <?php if($produit['top'] == 2): ?>
                    <div class="col-lg-4">
                        <a href="<?=LINK_ROOT.'vente/produit/'.$produit['id_produit']?>">
                            <img class="img-circle" src="<?=IMG_LINK_ROOT.$produit['img']?>" alt="Generic placeholder image">
                        </a>
                        <h3><?= $produit['value']?></h3>
                    </div><!-- /.col-lg-4 -->
                <?php endif; ?>
                <?php if($produit['top'] == 3): ?>
                    <div class="col-lg-4">
                        <a href="<?=LINK_ROOT.'vente/produit/'.$produit['id_produit']?>">
                            <img class="img-circle" src="<?=IMG_LINK_ROOT.$produit['img']?>" alt="Generic placeholder image">
                        </a>
                        <h3><?= $produit['value']?></h3>
                    </div><!-- /.col-lg-4 -->
                <?php endif; ?>
            <?php endforeach; ?>
        </div><!-- /.row -->
    </div><!-- /.container -->
</div>