<?php if(!empty($listeJeux)): foreach ($listeJeux as $jeu): ?>

	<div class="blog-post">
	    <h2 class="blog-post-title"><?=$jeu->nom?></h2>
	    <p class="blog-post-meta"><?=date("F j, Y",strtotime($jeu->update))?></p>
	    <p>
	    	<?=substr($jeu->description, 0, 50)?>
	    	<a href="<?=LINK_ROOT.'jeux/read/'.$jeu->id?>">read more</a>
	    </p>
	 </div>


<?php endforeach; else: ?>
	<div>Aucun jeu</div>
<?php endif; ?>



