<div id="WrapperAddProduit">
	
	<div class="row">
		<button class='btn btn-primary btn-xs col-xs-12 col-sm-6 col-md-8' id="btnAjouterProduitShowDiv">Ajouter un Produit</button>
	</div>
	<br/>
	<div class="ajouterProduitShowDiv">

		<form id="formImgProduit" enctype="multipart/form-data" action="<?= WEBSERVICE_ROOT.'/index.php' ?>" target="frameImgProduit" method="post">
			<div class="row">
				<div class="col-md-4">
					<label for="value">Nom du produit : </label>  
					<input name="value" type="text" id="value" required>
				</div>
				<div class="col-md-4">
					<label for="prix">Prix : </label>
					<input name="prix" type="text" id="prix" required>
				</div>
				<div class="col-md-4">
					<label for="ref">Ref : </label>
					<input name="ref" type="text" id="ref" required>
				</div>
			</div>
		
			<label for="inputFileImgProduitModifier" >image du produit</label>
			<input type="file" id="inputFileImgProduitModifier" name="img" />

			<div id="wrapperImgProduit">
                <img id='imgProduit'  alt='Image produit' style='width:150px; height:150px;' />
            </div>

            <input type="hidden" name="service" value="produit">
            <input type="hidden" name="method" value="insertProduit">


			<div class="row">
				<input type="submit" value="envoyer" id="uploadSubmitProd">
			</div>
		</form>
		<iframe  src="#" name="frameImgProduit"   id="frameImgProduit" >
        </iframe>	
	</div>

</div> <!-- fin de wrapperAddProduits-->


<h1>Liste des Produits disponibles</h1>

<div id="WrapperProduits">
<?php foreach ($produits as $produit): ?>
	<div>
		<div class="row" id="WrapperProduit<?= $produit['id_produit']?>">
			<div class="col-md-4">
			
				<a href="<?=LINK_ROOT.'vente/produit/'.$produit['id_produit']?>">Produit : <span id="labelValueProduit"><?= $produit['value']?></span></a>

			</div>
			<div class="col-md-4">
				Prix : <span id="labelPrixProduit"><?= $produit['prix']?></span> €
				Référence : <span id="labelRefProduit"><?= $produit['ref']?></span>
			</div>
			

			<div >
				<div id="wrapperImgProduit">
	                <img src="<?= $produit['img']?>" id='imgProduit'  alt='Image produit' style='width:150px; height:150px;' />
	            </div>
				<button class='btn btn-primary btn-xs col-md-offset-3 popupProduit' id="popupProduit<?=$produit['id_produit']?>" >Modifier ce Produit</button>
				<div class="row">
					<?=$produit['modifierpopup']?>
				</div>
			</div>
			
		</div>
	</div>
<?php endforeach; ?>
</div>	<!-- fin de wrapperProduits-->

