<div id="WrapperAddProduit">
	
	<div class="row">
		<button class='btn btn-primary btn-xs col-xs-12 col-sm-6 col-md-8' id="btnAjouterProduitShowDiv">Ajouter un Produit</button>
	</div>
	<br/>
	<div class="ajouterProduitShowDiv">
		<div class="row">
			<div class="col-md-4">
				<label for="value">Nom du produit : </label>  
				<input name="value" type="text" id="value">
			</div>
			<div class="col-md-4">
				<label for="prix">Prix : </label>
				<input name="prix" type="text" id="prix">
			</div>
			<div class="col-md-4">
				<label for="ref">Ref : </label>
				<input name="ref" type="text" id="ref">
			</div>
		</div>
		<div class="row">
			<button class="btn btn-warning col-md-1" name="btnAjouterProduit" type="submit" id="btnAjouterProduit">Valider</button>
		</div>
	</div>

</div> <!-- fin de wrapperAddProduits-->


<h1>Liste des Produits disponibles</h1>

<div id="WrapperProduits">
<?php foreach ($produits as $produit): ?>
	<div>
		<div class="row" id="WrapperProduit<?= $produit['id_produit']?>">
			<div class="col-md-4">
			
				<a href="<?=LINK_ROOT.'vente/produit/'.$produit['id_produit']?>">Produit : <span id="labelValueProduit"><?= $produit['value']?></span></a>

			</div>
			<div class="col-md-4">
				Prix : <span id="labelPrixProduit"><?= $produit['prix']?></span> €
				Référence : <span id="labelRefProduit"><?= $produit['ref']?></span>
			</div>
			

			<div >
				<button class='btn btn-primary btn-xs col-md-offset-3 popupProduit' id="popupProduit<?=$produit['id_produit']?>" >Modifier ce Produit</button>
				<div class="row">
					<?=$produit['modifierpopup']?>
				</div>

			</div>
			
		</div>
	</div>
<?php endforeach; ?>
</div>	<!-- fin de wrapperProduits-->

