




<div class="container containerView" id="WrapperProduits">
<h1>Liste des Produits disponibles</h1>

<?php foreach ($produits as $produit): ?>
	<div>
		<div class="row" id="WrapperProduit<?= $produit['id_produit']?>">
			<div class="col-md-4">
			
				<a href="<?=LINK_ROOT.'vente/produit/'.$produit['id_produit']?>">Produit : <span id="labelValueProduit"><?= $produit['value']?></span></a>

			</div>
			<div class="col-md-4">
				Prix : <span id="labelPrixProduit"><?= $produit['prix']?></span> €
				Référence : <span id="labelRefProduit"><?= $produit['ref']?></span>
			</div>
			

			<div class="col-md-4">

				<button class='btn btn-xs btn-primary' id="lierProduit" onclick="dissocierlierProduit(<?=$viewRecette['id_recette']?>, <?=$produit['id_produit']?>)">

					<?php if(array_key_exists('associe', $produit) && !empty($produit['associe'])): ?>
						Dissocier ce produit a la recette
					<?php else: ?>
						Lier ce Produit à la recette
					<?php endif; ?>
				</button>

			</div>
			
		</div>
	</div>
	<br>
<?php endforeach; ?>
</div>	<!-- fin de wrapperProduits-->