<?=$tinyMCECommentaire?>
<?=$message?>
<?php 

//var_dump($recettes);
//$viewRecette
?>

<script type="text/javascript">
    $("document").ready(function(){
        $("#divCom").hide();
        $("#btnAddCom").click(function(){
            console.log('ici');
            $("#divCom").show('slow');
            return false;
        });
    });

    

</script>



<?php


foreach ($viewRecette as $key => $champs){
    if($key!='ingredients' ){
        echo $key." : ".$champs.'<br>';
    }
}

var_dump($viewRecette['ingredients']);

foreach ($viewRecette['ingredients'] as $ingredient){
    foreach ($ingredient as $key => $champs){
        echo $key." : ".$champs.'<br>';
    }
}
echo '<hr><hr><hr>';

//commentaires
var_dump("viewCom", $viewCommentaires);
if(isset($viewCommentaires) && !is_null($viewCommentaires) ){
    foreach ($viewCommentaires as $commentaire){
        foreach ($commentaire as $key => $champs){
            echo $key." : ".$champs.'<br>';
        }
        echo '<hr>';
    }
}


?>


<input type="button" value="ajouter un commentaire"  id="btnAddCom"><br>


<div id="divCom">
    <form method="post">
        <textarea name="value">Un commentaire</textarea>
        <input type="hidden" name="id_recette" value="<?=$viewRecette['id_recette']?>">
        <input type="hidden" name="id_user" value="<?=$_SESSION ['user']['id_user']?>">
        <input type="submit" value="Envoyer"  name="btn">
    </form>
</div>
