<?=$message?>
<?php 
//var_dump($recette);


?>

<!--
array (size=25)
  'id_recette' => int 44
  'titre' => string 'Cupcake' (length=7)
  'value' => string 
  'tps_cuisson' => int 35
  'difficulte' => int 3
  'cout' => int 10
  'type' => string 'dessert' (length=7)
  'chef' => int 0
  'diabete' => int 0
  'ble' => int 1
  'lait' => int 1
  'oeuf' => int 1
  'arachide' => int 1
  'soja' => int 0
  'gluten' => int 0
  'note' => null
  'user_pseudo' => string 'Admin' (length=5)
  'categorie' => string 'Cuisine authentique' (length=19)
  'livre' => string 'Les petits plats de maman' (length=25)
  'livre_prix' => int 50
  'resto' => string 'Les petits plats de Samyn' (length=25)
  'resto_chef' => string 'Samyn' (length=5)
  'resto_prix' => int 4
  'ingredients' => 
    array (size=2)
      0 => 
        array (size=8)
          'id_liste' => int 25
          'id_ingredient' => int 8
          'id_recette' => int 44
          'id_unite' => int 2
          'value' => int 2
          'recette' => 
          'ingredients' => string 'oeufs' (length=5)
          'unite' => string 'Grammes' (length=7) -->

<hr class="featurette-divider">
<h1><?=$recette['categorie']?></h1>
<div class="row featurette">
    
    <div class="col-md-5">
        <img class="featurette-image img-responsive" src="<?=$recette['img']?>" alt="recette authentique">
        <h3>Liste des Ingrédients</h3>
        <?php foreach ($recette['ingredients'] as $ing): ?>
            <p class="lead"><?=$ing['ingredients']?> : <?=$ing['value']?> <?=$ing['unite']?></p>
        <?php endforeach ; ?>

    </div>
    <h2 class="featurette-heading"><?=$recette['titre']?></h2>
    <div class="col-md-7">
        
        <p class="lead">Difficulté : <?=$recette['difficulte']?> / 5</p>
        <p class="lead">Prix : <?=$recette['cout']?> €</p>
        <p class="lead"><?=$recette['value']?></p>
    </div>
</div>

 <!-- /END THE FEATURETTES -->