<?=$tinyMCECommentaire?>
<?=$message?>

<?php //var_dump($recette)?>

<script type="text/javascript">
    $("document").ready(function(){
        $("#divCom").hide();
        $("#btnAddCom").click(function(){
            //console.log('ici');
            $("#divCom").show('slow');
            return false;
        });
    });
</script>

<div class="row featurette recette">
    <h1><?=$recette['categorie']?></h1>
    <div class="col-md-5">
        <img class="featurette-image img-responsive" src="../../../..<?=$recette['img']?>" alt="<?=$recette['titre']?>">
        <h3>Liste des Ingrédients</h3>

        <!-- Si des ingrédients sont liés à la recette -->
        <?php if(!empty($recette['ingredients'])): foreach ($recette['ingredients'] as $ing): ?>
            <p class="lead"><?=$ing['ingredients']?> : <?=$ing['value']?> <?=$ing['unite']?></p>
        <?php endforeach; endif; ?>

    </div>
    <h2 class="featurette-heading"><?=$recette['titre']?></h2>
    <div class="col-md-7">
        
        <p class="lead">Difficulté : <?=$recette['difficulte']?> / 5</p>
        <p class="lead">Prix : <?=$recette['cout']?> €</p>
        <p class="lead"><?=$recette['value']?></p>
    </div>
    <div class="row">
        <div class="col-md-6" id="labelProduitRecette">
            Pour cette Recette, nos chefs ont utilisé : 
        </div>
    </div>
    <div class="row">
        <!-- Si desproduits sont liés à la recette -->
        <?php if(!empty($recette['produits'])): foreach ($recette['produits'] as $produit): ?>
            <div class="col-md-4" id="produitRecette">
                <?=$produit['value_produit']?>
                <img class="media-object" src="../../../..<?=$produit['img']?>" alt="<?=$produit['value_produit']?>">
                <p><?=$produit['prix']?> €</p>
                <p><?=$produit['ref']?></p>
            </div>
        <?php endforeach; endif; ?>
    </div>
</div>
<br>

<div class="row featurette recette" id="WrapperComms">
    <!-- Si des commentaires sont liés à la recette -->
    <?php if(!empty($recette['commentaires'])): foreach ($recette['commentaires'] as $com): ?>
        
        <hr>
        <div>
            <p><?= $com['value']?></p>
            <p><?= $com['note']?> / 5</p>
            <p><?= $com['pseudo']?></p>
            <p><?= $com['update']?></p>
        </div>

    <?php endforeach; endif; ?>
</div>


 <!-- /END THE FEATURETTES -->


<input class="btn btn-success" type="button" value="ajouter un commentaire"  id="btnAddCom"><br>


<div id="divCom">
        <textarea id="commValue"></textarea>
        <select id="noteValue">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
<!--         <input type="hidden" name="id_recette" value="<?=$recette['id_recette']?>">
<input type="hidden" name="id_user" value="<?=$_SESSION ['user']['id_user']?>"> -->
        <input type="submit" value="Envoyer"  id="addCommentaire">
</div>


    <marquee>
        testteette
    </marquee>
