<?=$message?>
<?php 


foreach($recettes as $recette): ?>
<!-- START THE FEATURETTES -->
    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
        <h2 class="featurette-heading"><?=$recette['categorie']?> <span class="text-muted"></span></h2>
        <p class="lead"><a href="<?=LINK_ROOT.'/recette/chef/'.$recette['id_recette']?>"> <?=$recette['titre']?></a></p>
        </div>
        <div class="col-md-5">
        <img class="featurette-image img-responsive" src="<?=WEB_ROOT?>/img/monde.jpg" alt="plat">
        </div>
    </div>
<?php endforeach;?>

 <!-- /END THE FEATURETTES -->
	


    <a href="<?=LINK_ROOT?>">Retour à l'accueil</a> - 
	
</form>
