<?=$message?>

<!-- START THE FEATURETTES -->
<hr class="featurette-divider">
<?php foreach($recettes as $recette): ?>
 <div class="col-md-4">
        <a href="<?=LINK_ROOT.'recette/indexcategorie/'.$recette['id_cat']?>"> <h1><?=$recette['value']?> <span class="text-muted"></span></h1></a>
        <!-- ../../../..<?=$recette['img']?> -->
        <p class="lead"><img class="img-thumbnail img-responsive" src="<?=WEB_ROOT?>/img/monde.jpg" alt="plat"></p>
        </div>  
<?php endforeach;?>

 <!-- /END THE FEATURETTES -->
	


    <a href="<?=LINK_ROOT?>">Retour à l'accueil</a> 
	
</form>

