<?=$message?>
<!-- START THE FEATURETTES -->
    
<h2 class="featurette-heading"><?=$titreCat?> <span class="text-muted"></span></h2>

<hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-7">
        <?php foreach($recettes as $recette): ?>
        <p class="lead"><a href="<?=LINK_ROOT.'recette/categorie/'.$categorie.'/'.$recette['id_recette']?>"> <?=$recette['titre']?></a></p>
        <?php endforeach;?>
        </div>
        <div class="col-md-5">
        <img class="featurette-image img-responsive" src="<?=$recette['img']?>" alt="plat">
        </div>
    </div>


 <!-- /END THE FEATURETTES -->
	


    <a href="<?=LINK_ROOT?>">Retour à l'accueil</a> - 
	
</form>
