 <?=$message?>

<div class="container containerView">
    <?php if(!empty($recettes)): ?>
        <h2>Voici les recettes correspondant à votre recherche : </h2>
        <div class="list-group" id="produitRecette">
        <?php foreach ($recettes as $recette): ?>

        
            <a class="list-group-item" href="<?=LINK_ROOT.'recette/categorie/'.$recette['slugtitre']?>">
            <h4 class="list-group-item-heading"><?=$recette['titre']?></h4>
            <p class="list-group-item-text">Categorie : <?=$recette['categorie']?></p>
            </a> 
        <?php endforeach;?>
        </div>
    <?php else:?>
        <div id="noMatch">
            <h2>Aucune recette ne correspond à votre recherche ! </h2>
            <h3>
                Si vous souhaitez voir toutes nos recettes, Rendez_vous : <a href="<?=LINK_ROOT.'recette/index'?>">ici</a> !
            </h3>
        </div>
    <?php endif; ?>
</div>
