<?=$message?>

<!-- START THE FEATURETTES -->
    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
        <h2 class="featurette-heading"><?=$recette['categorie']?> <span class="text-muted"></span></h2>
        <p class="lead"><?=$recette['titre']?></p>
        </div>
        <div class="col-md-5">
        <img class="featurette-image img-responsive" src="<?=WEB_ROOT?>/img/monde.jpg" alt="plat">
        </div>
    </div>

 <!-- /END THE FEATURETTES -->
	


    <a href="<?=LINK_ROOT?>">Retour à l'accueil</a> - 
	
</form>
