<?=$message?>

<!-- START THE FEATURETTES -->
<div class="container containerView">
	<div class="container-fluid">
		<br class="featurette-divider">
		<div class="row featurette">
			<div class="col-md-6">
				<h1><?php echo ucfirst($type);?></h1>
				<?php foreach($recettes as $recette): ?>
				<?php if($recette['type'] == $type): ?>
					
				<a class="linkCat" href="<?=LINK_ROOT.'recette/categorie/'.$recette['slugtitre']?>"> 
				<h4><?=$recette['titre']?></h4>
				</a>

				<?php endif; endforeach;?>
			</div>

			<img class="col-md-6 img-responsive img-thumbnail img" src="<?=WEB_ROOT.'img/type/'.$type?>.jpg" alt="<?=$type?>">
		</div>
	</div>
</div>
