<?=$urlWebService?>




<h1>Liste des Produits dans votre panier</h1>

<div id="WrapperProduits">

<?php foreach ($viewPanier as $produit):?>
	<hr>
	<div id="WrapperProduit<?=$produit['id_produit']?>">
		<div class="row" >
			<div class="col-md-8">
			
				<a href="<?=LINK_ROOT.'vente/produit/'.$produit['id_produit']?>">Produit : <span id="labelValueProduit"><?= $produit['value_produit']?></span></a>

			</div>
			<div class="col-md-4">
				Prix : <span id="labelPrixProduit"><?= $produit['prix_produit']?></span> €
				Référence : <span id="labelRefProduit"><?= $produit['ref_produit']?></span>
			</div>
			
			<div class="col-md-4">
				<form method="post" >
					<input type="hidden" name="id_user" value="<?= $_SESSION['user']['id_user'] ?>" />
					<input type="hidden" name="id_produit" value="<?= $_SESSION['user']['id_user'] ?>" />
					<input type="submit" name="action" value="delete" />
				</form>
			</div>


			
		</div>
	</div>
	
<?php endforeach; ?>

	-quelques additions ici,
	-pas de gestion de quantité
	-somme


	<div >
		<form method="post" action="<?=LINK_ROOT.''?>">
			<input type="hidden" name="id_user" value="<?= $_SESSION['user']['id_user'] ?>">
			<button class='btn btn-success col-md-3 col-md-offset-3 btnAcheterProduit' id="btnPasserCommande" >Finaliser la commande</button>
		</form>
	</div>
</div>	<!-- fin de wrapperProduits-->

<br/><br/><br/><br/>
<div class="row">
	<div class="col-md-8">



<!-- 
Test Insert : OK
<br/>

Nom du panier : <input name="value" type="text" id="value">
<br/>
Prix : <input name="prix" type="text" id="prix">
<br/>
Ref : <input name="ref" type="text" id="ref">
<br/>
<button class="btn btn-warning" name="btnAjouterProduit" type="submit" id="btnAjouterProduit">Valider</button>
</div>


</div>
 -->
