<?=$message?>

<form class="form-signin" method="post">
    <h2 class="form-signin-heading">
    	<?=$pageTitle?>
    </h2>
    <p>Êtes-vous sûr de vouloir supprimer définitivement votre compte ?</p>

    <input name="password" type="password" class="form-control form-password" placeholder="Password">


    <button name="btn" class="btn btn-lg btn-primary btn-block" type="submit"><?=$pageTitle?></button>
</form>