<?=$message?>
<form class="form-signin" method="post">
	<p>
        <a href="<?=LINK_ROOT?>">
            <img class="logoImg" src="<?=IMG_LINK_ROOT?>chefdesfourneauxlogo.png">
        </a>
    </p>
	<h1 class="form-signin-heading">
		<?=$pageTitle?>
	</h1>
	<p><h2>Êtes-vous sûr de vouloir supprimer définitivement votre compte ?</h2></p>

	<input name="password" type="password" class="form-control form-password" placeholder="Password">


	<button name="btn" class="btn btn-lg btn-primary btn-block" type="submit"><?=$pageTitle?></button>
</form>