<?=$message?>
<form class="form-signin" method="post">
    <h2 class="form-signin-heading">
    	<?=$pageTitle?>
    </h2>
    <input value="<?=(isset($_POST['nom']))?$_POST['nom']:''?>" name="nom" type="text" class="form-control" placeholder="Prénom" required autofocus>
    <input value="<?=(isset($_POST['prenom']))?$_POST['prenom']:''?>" name="prenom" type="text" class="form-control" placeholder="Nom de famille" required>
    <input value="<?=(isset($_POST['pseudo']))?$_POST['pseudo']:''?>" name="pseudo" type="text" class="form-control" placeholder="Pseudo" required>
    <input value="<?=(isset($_POST['mail']))?$_POST['mail']:''?>" name="mail" type="email" class="form-control" placeholder="Adresse email" required>

    <!--select>
        <option value="">Monsieur</option>
        <option value="">Madame</option>
    </select-->

    <input value="<?=(isset($_POST['date_naissance']))?$_POST['date_naissance']:''?>" name="date_naissance" type="date" class="form-control" placeholder="Date de naissance" required   > (AAAA/MM/JJ)
    <!--input value="<?=(isset($_POST['mail']))?$_POST['mail']:''?>" name="mail" type="email" class="form-control" placeholder="Email address" required>
    <input value="<?=(isset($_POST['mail']))?$_POST['mail']:''?>" name="mail" type="email" class="form-control" placeholder="Email address" required-->
    <input name="password" type="password" class="form-control form-password" placeholder="Password" required>
    <input name="confpassword" type="password" class="form-control" placeholder="Confirm Password" required>
    <button name="btn" class="btn btn-lg btn-primary btn-block" type="submit"><?=$pageTitle?></button>
    <a href="<?=LINK_ROOT?>">Retour au site</a> - 
    <a href="<?=LINK_ROOT?>user/login">Login</a>
</form>