<?=$message?>
<form class="form-signin" method="post">
    <h2 class="form-signin-heading">
    	<?=$pageTitle?>
    </h2>
    <input value="<?=(isset($_POST['nom']))?$_POST['nom']:''?>" name="nom" type="text" class="form-control" placeholder="First name" required autofocus>
    <input value="<?=(isset($_POST['prenom']))?$_POST['prenom']:''?>" name="prenom" type="text" class="form-control" placeholder="Last name" required>
    <input value="<?=(isset($_POST['mail']))?$_POST['mail']:''?>" name="mail" type="email" class="form-control" placeholder="Email address" required>
    <input name="password" type="password" class="form-control form-password" placeholder="Password" required>
    <input name="confpassword" type="password" class="form-control" placeholder="Confirm Password" required>
    <button name="btn" class="btn btn-lg btn-primary btn-block" type="submit"><?=$pageTitle?></button>
    <a href="<?=LINK_ROOT?>">Retour au site</a> - 
    <a href="<?=LINK_ROOT?>user/login">Login</a>
</form>