<?=$message?>
<form class="form-signin" method="post">
    <h2 class="form-signin-heading">
    	<?=$pageTitle?>
    </h2>
    <input name="mail" type="email" class="form-control" placeholder="Email address" required autofocus>
    <input name="password" type="password" class="form-control" placeholder="Password" required>
    <button name="btn" class="btn btn-lg btn-primary btn-block" type="submit"><?=$pageTitle?></button>
    <a href="<?=LINK_ROOT?>">Retour au site</a> - 
    <a href="<?=LINK_ROOT?>user/inscription">Inscription</a>
    <a href="<?=LINK_ROOT?>user/motdepasseoublie">Mot de passe oubli&eacute;</a>
</form>
