<!-- Page User/mot de passe oublié -->

<?=$message?>
<form class="form-signin" method="post">
    <p>
        <a href="<?=LINK_ROOT?>">
            <img class="logoImg" src="<?=IMG_LINK_ROOT?>chefdesfourneauxlogo.png">
        </a>
    </p>
    <h1 class="form-signin-heading">
    	<?=$pageTitle?>
    </h1>


    <!-- Mail -->
    <div id="msgError"></div>

    <input name="mail" id="mail" type="email" class="form-control" placeholder="Email address" required autofocus>
    <p>Repondre &agrave; la question pour recevoir votre nouveau mot de passe</p>
    <select name="id_questionsecrete" id="id_questionsecrete">
        <?php
        var_dump($questionSecretes);
        foreach ($questionSecretes as $questionSecrete) {?>
            <option value="<?=$questionSecrete['id_questionsecrete']?>" ><?=$questionSecrete['value']?></option>
        <?php } ?>
    </select>

    <input value="" name="reponsesecrete" type="text" class="form-control" placeholder="reponse secrete" required>

    <button name="btn" class="btn btn-lg btn-primary btn-block" type="submit">Valider</button>

    <a href="<?=LINK_ROOT?>">Retour au site</a> - 
    <a href="<?=LINK_ROOT?>user/login">Login</a>
</form>