<?=$message?>

<form class="form-signin" method="post">
    <h2 class="form-signin-heading">
    	<?=$pageTitle?>
    </h2>
    <!-- Nom -->
    <input value="<?=(isset($_SESSION['user']['nom']))?$_SESSION['user']['nom']:''?>" name="nom" type="text" class="form-control" placeholder="Nom" required autofocus>
    <!-- Prénom -->
    <input value="<?=(isset($_SESSION['user']['prenom']))?$_SESSION['user']['prenom']:''?>" name="prenom" type="text" class="form-control" placeholder="Prénom" required>
    <!-- Pseudo -->
    <input value="<?=(isset($_SESSION['user']['pseudo']))?$_SESSION['user']['pseudo']:''?>" name="pseudo" type="text" class="form-control" placeholder="Pseudo" required>
    <!-- Mail -->
    <input value="<?=(isset($_SESSION['user']['mail']))?$_SESSION['user']['mail']:''?>" name="mail" type="email" class="form-control" placeholder="Adresse Mail">
    <!-- Date de naissance -->
    <input value="<?=(isset($_SESSION['user']['date_naissance']))?$_SESSION['user']['date_naissance']:''?>" name="date_naissance" type="date" class="form-control" placeholder="Adresse Mail">
    <!-- Mot de passe actuel -->
    <input name="currentpassword" type="password" class="form-control" placeholder="Mot de passe actuel" required>

    <!-- Si l'utilisateur souhaite changer de mot de passe -->
    <fieldset>
        <legend>Changer de mot de passe (optionnel)</legend>
        <input name="password" type="password" class="form-control form-password" placeholder="Nouveau mot de passe">
        <input name="confpassword" type="password" class="form-control" placeholder="Confirmer nouveau mot de passe">
    </fieldset>

    
    <button name="btn" class="btn btn-lg btn-primary btn-block" type="submit"><?=$pageTitle?></button>
</form>
<a href="<?=LINK_ROOT?>user/delete">Supprimer mon compte</a>
