<?=$tinyMCECommentaire?>
<?=$message?>
<?php 

//var_dump($recettes);
//$viewRecette
?>

<script type="text/javascript">
    $("document").ready(function(){
        $("#divCom").hide();
        $("#btnAddCom").click(function(){
            //console.log('ici');
            $("#divCom").show('slow');
            return false;
        });
    });

    

</script>






<!-- START THE FEATURETTES -->
    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
        <h2 class="featurette-heading"><?=$recette['categorie']?> <span class="text-muted"></span></h2>
        <p class="lead"><?=$recette['titre']?></p>
        </div>
        <div class="col-md-5">
        <img class="featurette-image img-responsive" src="<?=WEB_ROOT?>/img/monde.jpg" alt="plat">
        </div>
    </div>

 <!-- /END THE FEATURETTES -->
	

<?php

echo '<hr><hr><hr>';

//commentaires
//var_dump("viewCom", $viewCommentaires);
if($viewCommentaires){//isset($viewCommentaires) && !is_null($viewCommentaires) ){
    foreach ($viewCommentaires as $commentaire){
        foreach ($commentaire as $key => $champs){
            echo $key." : ".$champs.'<br>';
        }
        echo '<hr>';
    }
}


?>


<input type="button" value="ajouter un commentaire"  id="btnAddCom"><br>


<div id="divCom">
    <form method="post">
        <textarea name="value">Un commentaire</textarea>
        <input type="hidden" name="id_recette" value="<?=$recette['id_recette']?>">
        <input type="hidden" name="id_user" value="<?=$_SESSION ['user']['id_user']?>">
        <input type="submit" value="Envoyer"  name="btn">
    </form>
</div>


    <a href="<?=LINK_ROOT?>">Retour à l'accueil</a> - 
	
</form>
