<div class="enconstruction">
	<p>
        <a href="<?=LINK_ROOT?>">
            <img class="logoImg" src="<?=IMG_LINK_ROOT?>chefdesfourneauxlogo.png">
        </a>
    </p>
	<div class="container jumbotron">
	  	<h1>Page en construction</h1>
	  	<p>Cette page sera bientôt disponible</p>
	  	<p>
	  		<a class="btn btn-primary btn-lg" href="<?=LINK_ROOT?>">Retour au site</a>
	  	</p>
	</div>
</div>
